### ISSUE TITLE
Find and Fix Bugs | Start here

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Hacktoberfest#1]
## Background

This issue provides directions on how you can contribute to one of our Call for Code for Racial Justice repositories by documenting bugs and fixing them. Please keep this issue open.

## Tasks

- [ ] Check out the open issues, ensure you're not replicating existing issues
- [ ] Read & follow the instructions in the Getting Started Section of the project of your choice, [find all projects here](https://call-for-code-for-racial-justice.github.io/Hacktoberfest/#/projects/legit-info). 

As you run across any bugs (error messages, etc)
- [ ] if your issue is more of a suggestion for improving the UI go to this issue instead
- [ ] create a new issue using the bug template
- [ ] label it `hacktoberfest` `bug`
- [ ] Discuss the bug you found in the issue, maintainers of the project will also comment on your issue. 

If you are able to fix the bug
- [ ] comment in the issue to claim the issue
- [ ] add details on your proposed fix to the issue
- [ ] Discuss the issue  maintainers of the project will also comment on your issue.
- [ ] Fork the repository.
- [ ] Commit your changes to your fork & submit your pull request
- [ ] Handle any feedback before the request is merged.
- [ ] PR merged by team
- [ ] Congratulations! 

If you are unfamilar with pull requests, committing code on Github, we recommend you check out our free course on open source: [ibm.biz/opensourcecourse](ibm.biz/opensourcecourse)
