### ISSUE TITLE
New Feature Idea? | Start here

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Hacktoberfest#7]
## Background

This issue provides directions on how you can contribute to our Call for Code for Racial repositories. Contributions should be made to those repositories and not here. 

## Tasks

- [ ] Check out the open issues, ensure you're not replicating existing issues
- [ ] Read & follow the instructions in the Getting Started section of the readme.md to set the solution up. [Find all projects here.  ](https://call-for-code-for-racial-justice.github.io/Hacktoberfest/#/projects/legit-info)

As you run the solution, note any updates to current UI features that would improve the user experience with this solution
- [ ] create a new issue using the feature update template (if it exists or find the issue to create it and use it). 
- [ ] label it 'hacktoberfest', 
- [ ] Discuss your suggested feature the issue with  the team. 

If you are able to implement the solution
- [ ] comment in the issue to claim the issue
- [ ] add details on your proposed fix to the issue
- [ ] Discuss the issue  maintainers of the project will also comment on your issue.
- [ ] Fork the repository.
- [ ] Commit your changes to your fork & submit your pull request
- [ ] Handle any feedback before the request is merged.
- [ ] PR merged by team
- [ ] Congratulations! 
-
If you are unfamilar with pull requests, committing code on Github, we recommend you check out our free course on open source: ibm.biz/opensourcecourse
